package render

import (
	"fmt"
	"io"
	"strings"

	"github.com/itsveems/permadiff/internal/classify"
)

// Markdown writes a GitHub-PR-comment-ready report.
func Markdown(w io.Writer, rep *classify.Report) {
	fmt.Fprintf(w, "## permadiff — plan noise report\n\n")
	noisePart := plural(rep.Noise, "perma-diff no-op")
	if rep.Noise > 0 {
		noisePart += " (with fixes)"
	}
	fmt.Fprintf(w, "**%s: %s · %s**\n\n", plural(rep.Total, "change"), noisePart, plural(rep.RealTotal(), "real change"))

	noise := filter(rep, classify.ClassNoise)
	if len(noise) > 0 {
		fmt.Fprintf(w, "### 🔇 Perma-diff noise (%d)\n\n", rep.Noise)
		fmt.Fprintf(w, "These in-place updates are semantically identical before and after — provider/API normalisation artifacts, not real changes. Each comes with the fix that makes it disappear.\n\n")
		for _, rr := range noise {
			renderNoiseMarkdown(w, rr)
		}
	}

	real := append(filter(rep, classify.ClassReal), filter(rep, classify.ClassLikelyNoise)...)
	sortByAddress(real)
	if len(real) > 0 {
		fmt.Fprintf(w, "### ⚠️ Real changes (%d)\n\n", rep.RealTotal())
		fmt.Fprintf(w, "Nothing below is suppressed or judged — review as usual.\n\n")
		for _, rr := range real {
			renderRealMarkdown(w, rr)
		}
		fmt.Fprintln(w)
	}

	if rep.Total == 0 {
		fmt.Fprintf(w, "_Plan contains no changes._\n\n")
	}
	fmt.Fprintf(w, "<sub>Generated by <a href=\"https://github.com/itsveems/permadiff\">permadiff</a>. Run <code>permadiff --explain &lt;address&gt;</code> locally for full canonicalisation reasoning.</sub>\n")
}

func renderNoiseMarkdown(w io.Writer, rr classify.ResourceReport) {
	attrs := make([]string, 0, len(rr.Findings))
	for _, f := range rr.Findings {
		attrs = append(attrs, "<code>"+mdHTML(f.Attribute)+"</code>")
	}
	fmt.Fprintf(w, "<details>\n<summary><code>~ %s</code> — %s (%s)</summary>\n\n",
		mdHTML(rr.Address), strings.Join(attrs, ", "), string(rr.Confidence)+" confidence")
	for _, g := range groupByPattern(rr.Findings) {
		f := g.findings[0]
		title, why, fix := findingTexts(f)
		escaped := make([]string, len(g.attrs))
		for i, a := range g.attrs {
			escaped[i] = mdCode(a)
		}
		fmt.Fprintf(w, "**`%s` — %s.** %s\n\n", strings.Join(escaped, "`, `"), title, why)
		if fix != "" {
			fmt.Fprintf(w, "**Fix:** %s\n\n", fix)
		}
		if f.Pattern != nil && f.Pattern.Fix.HCLBefore != "" {
			fmt.Fprintf(w, "```hcl\n# before\n%s\n# after\n%s\n```\n\n",
				strings.TrimRight(f.Pattern.Fix.HCLBefore, "\n"),
				strings.TrimRight(f.Pattern.Fix.HCLAfter, "\n"))
		}
		if f.Pattern != nil && f.Pattern.Fix.Warning != "" {
			fmt.Fprintf(w, "> ⚠️ %s\n\n", f.Pattern.Fix.Warning)
		}
	}
	fmt.Fprintf(w, "</details>\n\n")
}

func renderRealMarkdown(w io.Writer, rr classify.ResourceReport) {
	symbol := "~"
	switch {
	case rr.Action == "create":
		symbol = "+"
	case rr.Action == "delete":
		symbol = "-"
	case strings.HasPrefix(rr.Action, "replace"):
		symbol = "±"
	}
	fmt.Fprintf(w, "- `%s` **`%s`** (%s)", symbol, mdCode(rr.Address), rr.Action)
	if !rr.Analyzed {
		fmt.Fprintln(w)
		return
	}
	var parts []string
	for _, f := range rr.Findings {
		attr := mdCode(f.Attribute)
		switch {
		case f.NoOp && rr.Class == classify.ClassLikelyNoise:
			parts = append(parts, fmt.Sprintf("`%s` ◐ _possible perma-diff (%s confidence): %s_", attr, rr.Confidence, findingTitle(f)))
		case f.NoOp:
			parts = append(parts, fmt.Sprintf("`%s` _(no-op: %s)_", attr, findingTitle(f)))
		default:
			parts = append(parts, fmt.Sprintf("`%s`: %s → %s", attr,
				mdValue(f.Before, f.Sensitive), mdRightValue(f)))
		}
		if f.Note != "" {
			parts = append(parts, "⚠️ "+f.Note)
		}
	}
	if len(parts) > 0 {
		fmt.Fprintf(w, " — %s", strings.Join(parts, "; "))
	}
	fmt.Fprintln(w)
}

func mdValue(v any, sensitive bool) string {
	s := compactValue(v, sensitive)
	if s == redacted {
		return "_" + s + "_"
	}
	return "`" + strings.ReplaceAll(s, "`", "'") + "`"
}

func mdRightValue(f classify.AttrFinding) string {
	if f.Unknown {
		return "_(known after apply)_"
	}
	return mdValue(f.After, f.Sensitive)
}
